#!/usr/bin/env python3

import json
import shutil

import subprocess as sp

build_gradle_kts = """
/*
 * This file was generated by the Gradle 'init' task.
 * Well, it was then re-generated by a Python script `nix/build_gradle_lock_for_bc.py`
 */

plugins {{
    id("java-library")
}}

repositories {{
    mavenCentral()
}}

dependencies {{
    // https://mvnrepository.com/artifact/org.bouncycastle/{provider}/{version}
    api("org.bouncycastle:{provider}:{version}")
    // https://mvnrepository.com/artifact/commons-cli/commons-cli
    // We need 1.5.0, as for some reason 1.6.0 doesn't work (arguments don't ger parsed properly).
    api("commons-cli:commons-cli:1.5.0")
    // https://mvnrepository.com/artifact/org.yaml/snakeyaml
    api("org.yaml:snakeyaml:2.2")
    // https://mvnrepository.com/artifact/com.klinec/jcardsim
    api("com.klinec:jcardsim:3.0.5.11")

    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit-pioneer:junit-pioneer:2.2.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}}

java {{
    sourceCompatibility = JavaVersion.VERSION_15
}}
"""


def main():
    with open("nix/bouncycastle_provider_version.json", "r") as handle:
        tags = json.load(handle)

    for tag, values in tags.items():
        print(f"Processing: {tag}")
        provider = values["provider"]
        version = values["version"]

        with open(
            f"nix/bouncycastle/build-{provider}_{version}.gradle.kts", "w"
        ) as handle:
            handle.write(build_gradle_kts.format(provider=provider, version=version))

        try:
            out = sp.check_output(
                ["nix", "run", "github:tadfisher/gradle2nix/v2", "--"]
            )
            shutil.copyfile("./gradle.lock", f"./nix/bouncycastle/gradle_{tag}.lock")
            print(f"\tOK")
        except sp.CalledProcessError:
            print(f"\tError: gradle2nix")


if __name__ == "__main__":
    main()
